### ISSUE TITLE
Replace Superset with Metabase

### ISSUE THREAD

**Issue by stndn** [stndn/garudata#18]
With reference to https://github.com/apache/superset/issues/5570 and https://github.com/apache/superset/discussions/19182, Superset is currently missing the feature to display metrics in charts with as-is value, without aggregation.

Since the non-aggregated values is important to some of the charts, we should explore another BI tool to accomplish our goals.

Currently looking at [Metabase](https://www.metabase.com/) as the alternative business intelligence tool.

**Comment by jkryanchou** [comment]
I make same wish. It should provide a custom SQL options or advance option to archive that

**Comment by stndn** [comment]
Replaced in PR #21 . Will explore Metabase's capabilities moving forward.
